import type { V2Viewpoint, V2Workout } from "./types";

export const V2_VIEWPOINTS: V2Viewpoint[] = [
  {
    id: "coach",
    label: "Coach",
    camera: "trainer-facing",
    showCoach: true,
    showAthleteCamera: false,
    compactHud: false,
  },
  {
    id: "manual",
    label: "Manual",
    camera: "coach-eye",
    showCoach: false,
    showAthleteCamera: true,
    compactHud: false,
  },
  {
    id: "shadow",
    label: "Shadow",
    camera: "follow-along",
    showCoach: true,
    showAthleteCamera: false,
    compactHud: false,
  },
  {
    id: "glasses",
    label: "Glasses",
    camera: "first-person",
    showCoach: true,
    showAthleteCamera: false,
    compactHud: true,
  },
];

export const V2_WORKOUTS: V2Workout[] = [
  {
    id: "push-arms",
    title: "Push + Arm Finisher",
    focus: "Shoulders · chest · triceps",
    exercises: [
      {
        id: "shoulder-press",
        name: "Shoulder Press",
        category: "strength",
        sets: 3,
        reps: "8–10",
        repRange: [8, 10],
        restSeconds: 90,
        equipment: ["dumbbells", "supported bench"],
        motionKey: "shoulderPress",
        cues: ["Drive up", "Control down", "Keep the path clean"],
        warmupStyle: "compound",
        loadClass: "upper",
      },
      {
        id: "incline-press",
        name: "Incline Press",
        category: "strength",
        sets: 3,
        reps: "8–10",
        repRange: [8, 10],
        restSeconds: 90,
        equipment: ["incline bench", "dumbbells"],
        motionKey: "inclinePress",
        cues: ["Press strong", "Control down", "Shoulders stay set"],
        warmupStyle: "compound",
        loadClass: "upper",
      },
      {
        id: "chest-press",
        name: "Chest Press",
        category: "strength",
        sets: 3,
        reps: "10–12",
        repRange: [10, 12],
        restSeconds: 75,
        equipment: ["chest press"],
        motionKey: "chestPress",
        cues: ["Chest up", "Drive forward", "Smooth controlled reps"],
        warmupStyle: "compound",
        loadClass: "machine",
      },
      {
        id: "lateral-raise",
        name: "Lateral Raise / Cable Raise",
        category: "strength",
        sets: 3,
        reps: "12–15",
        repRange: [12, 15],
        restSeconds: 60,
        equipment: ["dumbbells"],
        motionKey: "lateralRaise",
        cues: ["No swinging", "Raise wide", "Stop at shoulder height"],
        warmupStyle: "small",
        loadClass: "upper",
      },
      {
        id: "triceps-pressdown",
        name: "Rope Triceps Pressdown",
        category: "strength",
        sets: 3,
        reps: "10–15",
        repRange: [10, 15],
        restSeconds: 60,
        equipment: ["cable stack", "rope attachment"],
        motionKey: "tricepsPressdown",
        cues: ["Elbows pinned", "Squeeze at the bottom", "Stay controlled"],
        warmupStyle: "small",
        loadClass: "machine",
      },
    ],
  },
  {
    id: "pull-arms",
    title: "Pull + Arm Finisher",
    focus: "Back · rear delts · biceps",
    exercises: [
      {
        id: "lat-pulldown",
        name: "Lat Pulldown",
        category: "strength",
        sets: 3,
        reps: "8–10",
        repRange: [8, 10],
        restSeconds: 90,
        equipment: ["lat pulldown"],
        motionKey: "latPulldown",
        cues: ["Pull down", "Drive the elbows", "Stay controlled"],
        warmupStyle: "compound",
        loadClass: "machine",
      },
      {
        id: "seated-row",
        name: "Seated Row",
        category: "strength",
        sets: 3,
        reps: "10–12",
        repRange: [10, 12],
        restSeconds: 90,
        equipment: ["cable row"],
        motionKey: "seatedRow",
        cues: ["Chest up", "Full stretch", "Squeeze the back"],
        warmupStyle: "compound",
        loadClass: "machine",
      },
      {
        id: "bent-over-row",
        name: "Bent-Over Row",
        category: "strength",
        sets: 3,
        reps: "8–10",
        repRange: [8, 10],
        restSeconds: 90,
        equipment: ["barbell or dumbbells"],
        motionKey: "bentOverRow",
        cues: ["Brace hard", "Hinge back", "Row clean"],
        warmupStyle: "compound",
        loadClass: "upper",
      },
      {
        id: "face-pull",
        name: "Face Pull",
        category: "strength",
        sets: 3,
        reps: "12–15",
        repRange: [12, 15],
        restSeconds: 60,
        equipment: ["cable stack", "rope attachment"],
        motionKey: "facePull",
        cues: ["Pull high", "Rear delts", "Keep it clean"],
        warmupStyle: "small",
        loadClass: "machine",
      },
      {
        id: "curl",
        name: "Dumbbell / Cable Curl",
        category: "strength",
        sets: 3,
        reps: "10–15",
        repRange: [10, 15],
        restSeconds: 60,
        equipment: ["dumbbells"],
        motionKey: "dumbbellCurl",
        cues: ["No swinging", "Curl clean", "Squeeze biceps"],
        warmupStyle: "small",
        loadClass: "upper",
      },
    ],
  },
  {
    id: "cardio-core",
    title: "Cardio / Shadow Boxing + Core",
    focus: "Conditioning · calorie burn · core",
    exercises: [
      {
        id: "boxing-flow",
        name: "Shadow Boxing",
        category: "boxing",
        sets: 8,
        reps: "6–10 rounds · 1 min work / 30 sec rest",
        seconds: 60,
        restSeconds: 30,
        motionKey: "boxingCombination",
        cues: ["Hands up", "Tight core", "Fast but controlled"],
        warmupStyle: "none",
        loadClass: "bodyweight",
      },
      {
        id: "treadmill-hiit",
        name: "Treadmill HIIT / Incline Walk",
        category: "cardio",
        sets: 1,
        reps: "10–20 min intervals",
        restSeconds: 0,
        equipment: ["treadmill"],
        motionKey: "treadmillWalk",
        cues: ["Work hard", "Recover under control", "No jumping"],
        warmupStyle: "none",
        loadClass: "bodyweight",
      },
      {
        id: "hanging-knee-raise",
        name: "Hanging Knee Raise",
        category: "core",
        sets: 3,
        reps: "8–12",
        repRange: [8, 12],
        restSeconds: 60,
        equipment: ["pull-up station"],
        motionKey: "hangingKneeRaise",
        cues: ["No swinging", "Knees up", "Abs tight"],
        warmupStyle: "none",
        loadClass: "bodyweight",
      },
      {
        id: "v-sit-crunch",
        name: "V-Sit Crunch",
        category: "core",
        sets: 3,
        reps: "10–15",
        repRange: [10, 15],
        restSeconds: 60,
        motionKey: "vSitCrunch",
        cues: ["Brace hard", "Control the reps", "Stay compact"],
        warmupStyle: "none",
        loadClass: "bodyweight",
      },
      {
        id: "side-core",
        name: "Side Crunch / Plank",
        category: "core",
        sets: 3,
        reps: "10–15/side or 30–45 sec hold",
        restSeconds: 45,
        motionKey: "sidePlank",
        cues: ["Brace", "Hold strong", "No rushing"],
        warmupStyle: "none",
        loadClass: "bodyweight",
      },
    ],
  },
  {
    id: "legs",
    title: "Legs",
    focus: "Squat pattern · lunge · press · quads · calves",
    exercises: [
      {
        id: "back-squat",
        name: "Back Squat",
        category: "strength",
        sets: 3,
        reps: "6–8",
        repRange: [6, 8],
        restSeconds: 120,
        equipment: ["barbell", "squat rack"],
        motionKey: "backSquat",
        cues: ["Brace core", "Drive up", "Keep clean depth"],
        warmupStyle: "compound",
        loadClass: "lower",
      },
      {
        id: "reverse-lunge",
        name: "Reverse Lunge",
        category: "strength",
        sets: 3,
        reps: "8–10 per leg",
        repRange: [8, 10],
        restSeconds: 90,
        equipment: ["dumbbells"],
        motionKey: "reverseLunge",
        cues: ["Step back", "Stay tall", "Control each side"],
        warmupStyle: "compound",
        loadClass: "lower",
      },
      {
        id: "leg-press",
        name: "Leg Press",
        category: "strength",
        sets: 3,
        reps: "10–12",
        repRange: [10, 12],
        restSeconds: 90,
        equipment: ["leg press"],
        motionKey: "legPress",
        cues: ["Full foot", "Controlled drive", "No bouncing"],
        warmupStyle: "compound",
        loadClass: "machine",
      },
      {
        id: "leg-extension",
        name: "Leg Extension",
        category: "strength",
        sets: 3,
        reps: "12–15",
        repRange: [12, 15],
        restSeconds: 60,
        equipment: ["leg extension"],
        motionKey: "legExtension",
        cues: ["Lift smooth", "Squeeze quads", "Control down"],
        warmupStyle: "small",
        loadClass: "machine",
      },
      {
        id: "calf-raise",
        name: "Standing / Seated Calf Raise",
        category: "strength",
        sets: 3,
        reps: "12–20",
        repRange: [12, 20],
        restSeconds: 60,
        equipment: ["calf station"],
        motionKey: "calfRaise",
        cues: ["Full stretch", "Pause at top", "Hard squeeze"],
        warmupStyle: "small",
        loadClass: "lower",
      },
    ],
  },
  {
    id: "weak-point-pump",
    title: "Optional Weak Point Pump",
    focus: "Arms · shoulders · back detail",
    exercises: [
      {
        id: "pump-lateral-raise",
        name: "Lateral Raise",
        category: "strength",
        sets: 2,
        reps: "12–15",
        repRange: [12, 15],
        restSeconds: 45,
        equipment: ["dumbbells"],
        motionKey: "lateralRaise",
        cues: ["Light load", "No swinging", "Clean burn"],
        warmupStyle: "small",
        loadClass: "upper",
        optional: true,
      },
      {
        id: "pump-curl",
        name: "Curl",
        category: "strength",
        sets: 2,
        reps: "12–15",
        repRange: [12, 15],
        restSeconds: 45,
        equipment: ["dumbbells"],
        motionKey: "dumbbellCurl",
        cues: ["Strict reps", "Squeeze", "Keep it lighter"],
        warmupStyle: "small",
        loadClass: "upper",
        optional: true,
      },
      {
        id: "pump-face-pull",
        name: "Face Pull",
        category: "strength",
        sets: 2,
        reps: "12–15",
        repRange: [12, 15],
        restSeconds: 45,
        equipment: ["cable stack"],
        motionKey: "facePull",
        cues: ["Rear delts", "Pull high", "No momentum"],
        warmupStyle: "small",
        loadClass: "machine",
        optional: true,
      },
    ],
  },
];

export function viewpointFor(id: string) {
  return V2_VIEWPOINTS.find((v) => v.id === id) ?? V2_VIEWPOINTS[0];
}
