/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as GlassesRouteImport } from './routes/glasses'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutDayRouteImport } from './routes/workout.$day'
import { Route as CoachDayRouteImport } from './routes/coach.$day'
import { Route as ApiPublicCoachSpeechRouteImport } from './routes/api/public/coach-speech'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassesRoute = GlassesRouteImport.update({
  id: '/glasses',
  path: '/glasses',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDayRoute = WorkoutDayRouteImport.update({
  id: '/workout/$day',
  path: '/workout/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachDayRoute = CoachDayRouteImport.update({
  id: '/coach/$day',
  path: '/coach/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCoachSpeechRoute = ApiPublicCoachSpeechRouteImport.update({
  id: '/api/public/coach-speech',
  path: '/api/public/coach-speech',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/glasses': typeof GlassesRoute
  '/nutrition': typeof NutritionRoute
  '/presentation': typeof PresentationRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/coach/$day': typeof CoachDayRoute
  '/workout/$day': typeof WorkoutDayRoute
  '/api/public/coach-speech': typeof ApiPublicCoachSpeechRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/glasses': typeof GlassesRoute
  '/nutrition': typeof NutritionRoute
  '/presentation': typeof PresentationRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/coach/$day': typeof CoachDayRoute
  '/workout/$day': typeof WorkoutDayRoute
  '/api/public/coach-speech': typeof ApiPublicCoachSpeechRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/glasses': typeof GlassesRoute
  '/nutrition': typeof NutritionRoute
  '/presentation': typeof PresentationRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/coach/$day': typeof CoachDayRoute
  '/workout/$day': typeof WorkoutDayRoute
  '/api/public/coach-speech': typeof ApiPublicCoachSpeechRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/display'
    | '/glasses'
    | '/nutrition'
    | '/presentation'
    | '/program'
    | '/progress'
    | '/safety'
    | '/settings'
    | '/coach/$day'
    | '/workout/$day'
    | '/api/public/coach-speech'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/display'
    | '/glasses'
    | '/nutrition'
    | '/presentation'
    | '/program'
    | '/progress'
    | '/safety'
    | '/settings'
    | '/coach/$day'
    | '/workout/$day'
    | '/api/public/coach-speech'
  id:
    | '__root__'
    | '/'
    | '/display'
    | '/glasses'
    | '/nutrition'
    | '/presentation'
    | '/program'
    | '/progress'
    | '/safety'
    | '/settings'
    | '/coach/$day'
    | '/workout/$day'
    | '/api/public/coach-speech'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisplayRoute: typeof DisplayRoute
  GlassesRoute: typeof GlassesRoute
  NutritionRoute: typeof NutritionRoute
  PresentationRoute: typeof PresentationRoute
  ProgramRoute: typeof ProgramRoute
  ProgressRoute: typeof ProgressRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  CoachDayRoute: typeof CoachDayRoute
  WorkoutDayRoute: typeof WorkoutDayRoute
  ApiPublicCoachSpeechRoute: typeof ApiPublicCoachSpeechRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glasses': {
      id: '/glasses'
      path: '/glasses'
      fullPath: '/glasses'
      preLoaderRoute: typeof GlassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$day': {
      id: '/workout/$day'
      path: '/workout/$day'
      fullPath: '/workout/$day'
      preLoaderRoute: typeof WorkoutDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$day': {
      id: '/coach/$day'
      path: '/coach/$day'
      fullPath: '/coach/$day'
      preLoaderRoute: typeof CoachDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/coach-speech': {
      id: '/api/public/coach-speech'
      path: '/api/public/coach-speech'
      fullPath: '/api/public/coach-speech'
      preLoaderRoute: typeof ApiPublicCoachSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisplayRoute: DisplayRoute,
  GlassesRoute: GlassesRoute,
  NutritionRoute: NutritionRoute,
  PresentationRoute: PresentationRoute,
  ProgramRoute: ProgramRoute,
  ProgressRoute: ProgressRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  CoachDayRoute: CoachDayRoute,
  WorkoutDayRoute: WorkoutDayRoute,
  ApiPublicCoachSpeechRoute: ApiPublicCoachSpeechRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}